# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site infor for SEO tag
title: "micbon"
description: "Michael J. Moon"
url: "https://www.micbon.com"
baseurl: "/"
author: "Michael J. Moon"

# Use collections dir
collections_dir: collections
collections:
    webs:
        ouput: false

# Sass
sass:
    sass_dir: _sass
    style: compressed

# Build settings
markdown: kramdown
highlighter: rouge
permalink: none
plugins:
    - jekyll-seo-tag
